version: '3.1'

services:
  db:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - "~/storage/postgres_connector:/var/lib/postgresql/data"
  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  # connector:
  #   build: ../connector
  #   hostname: connector
  #   network_mode: "host"
  #   container_name: connector
  #   restart: always
  #   volumes:
  #     - "~/BMP-IPFIX-Visualization/connector:/code"
  #   depends_on:
  #     - db