version: '3.1'

services:
  db:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080