version: '3.1'

services:
  timescale:
    image: timescale/timescaledb:latest-pg12
    hostname: timescale
    container_name: timescale
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - "~/storage/postgres_connector:/var/lib/postgresql/data"
      - ../docker/scripts/postgres:/docker-entrypoint-initdb.d/
    command: -cmax_locks_per_transaction=400

  adminer_dev:
    image: adminer
    hostname: adminer_dev
    container_name: adminer_dev
    restart: always
    ports:
      - 8081:8080

  # connector:
  #   build: ../connector
  #   hostname: connector
  #   network_mode: "host"
  #   container_name: connector
  #   restart: always
  #   volumes:
  #     - "~/BMP-IPFIX-Visualization/connector:/code"
  #   depends_on:
  #     - db