apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect-deployment
  labels:
    app: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: marcotollini/cosmos-cp-kafka-connect:6.0.1-1
          resources:
            requests:
              memory: "1024Mi"
              cpu: "2"
            limits:
              memory: "1024Mi"
              cpu: "2"
          ports:
          - containerPort: 28083
          env:
            - name: CONNECT_REST_PORT
              value: "28083"
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: b-1.cosmos-kafka.h4i217.c2.kafka.eu-central-1.amazonaws.com:9092,b-2.cosmos-kafka.h4i217.c2.kafka.eu-central-1.amazonaws.com:9092
            - name: CONNECT_GROUP_ID
              value: kafka-connect
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: kafka-connect-config
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: kafka-connect-offsets
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: kafka-connect-status
            - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_KEY_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: localhost
            - name: CONNECT_LOG4J_ROOT_LOGLEVEL
              value: INFO
            - name: CONNECT_PLUGIN_PATH
              value: /usr/share/java,/etc/kafka-connect/jars
            - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
              value: http://a4690ab60aff44356b4b8801d9fa11b3-8313bf3cdaa91fa0.elb.eu-central-1.amazonaws.com
            - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
              value: http://a4690ab60aff44356b4b8801d9fa11b3-8313bf3cdaa91fa0.elb.eu-central-1.amazonaws.com
            - name: CONNECT_INTERNAL_KEY_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_INTERNAL_VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  externalTrafficPolicy: Local
  selector:
    app: kafka-connect
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 28083
