apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.25"
            limits:
              memory: "1024Mi"
              cpu: "1"
          # command: ["/bin/bash"]
          # args: ["-c", "sleep 1000"]
          ports:
          - containerPort: 3422
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: bmp@bmp.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: password
            - name: PGADMIN_LISTEN_PORT
              value: "3422"
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  externalTrafficPolicy: Local
  selector:
    app: pgadmin
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3422